### ISSUE TITLE
Redirect type is not working

### ISSUE THREAD

**Issue by malpertuis** [BlueTeaNL/AjaxResponseBundle#4]
Redirects from a controller isn't working

**Comment by piwi91** [comment]
Hi @malpertuis ,

Can you give us an example what your doing inside your controller and how you create the AJAX call?

**Comment by malpertuis** [comment]
return new AjaxResponse($this->generateUrl('homepage'), AjaxResponse::TYPE_REDIRECT);

$(document).ajaxProtocol("call", {
    url: Routing.generate('ims_portal_lesson_lesson_editor_step_new', {
        'slug': 'training',
        'lessonSlug': 'lesson'
    }),
    type: "GET"
});

**Comment by piwi91** [comment]
This issue is resolved in 1a21fcef5b0e253f1481a4672d7b71edcfb51279
