### ISSUE TITLE
TypeError: $.widget is not a function

### ISSUE THREAD

**Issue by almare** [BlueTeaNL/AjaxResponseBundle#6]
I used your bundle to get the AjaxResponse functionality, but after adding your bundle I get the following error. 
`TypeError: $.widget is not a function`

Do I miss something?

**Comment by almare** [comment]
I found the problem for this error. This is caused by the missing
` }(jQuery));`
at the end of the ajaxProtocol.js. After changing this the error is gone. But now I get the next error 
`TypeError: $(...).ajaxProtocol is not a function`.

**Comment by piwi91** [comment]
Hi @almare ,
You should have jQuery UI Widget dependency installed: https://jqueryui.com/widget/
