### ISSUE TITLE
When receiving flash message, no titles are added to the pnotify.

### ISSUE THREAD

**Issue by Matts** [BlueTeaNL/AjaxResponseBundle#7]
When trying to figure out why we were missing the titles on messages sent by the BE, I noticed that within the ajaxProtocol.js _handleFlashbag method, there is no title assigned.

Optimally, this function would be an option for some kind of callback to customize, since at this moment there seem to be discrepancies between messages generated via JS and Flash's

**Comment by tomcoonen** [comment]
Hi @Matts, feel free to submit a PR.
